export const ADMIN_ENTITIES = {
  // 1. Dược phẩm & Kho
  thuoc: {
    title: 'Danh sách thuốc',
    resource: 'thuoc',
    label: 'thuốc',
    group: 'Dược phẩm & Kho',
    searchKeys: ['ten_thuoc', 'ma_sku', 'loai_ke_don', 'so_dang_ky'],
    fields: [
      { name: 'ten_thuoc', label: 'Tên thuốc', required: true },
      { name: 'ma_sku', label: 'Mã SKU' },
      { name: 'gia_ban', label: 'Giá bán (VNĐ)', keyboardType: 'numeric', required: true },
      { name: 'so_luong_ton', label: 'Số lượng tồn', keyboardType: 'numeric', required: true },
      { name: 'don_vi_tinh', label: 'Đơn vị tính (Hộp/Vỉ/Tuýp/Lọ)' },
      { name: 'loai_ke_don', label: 'Loại (khong_ke_don / ke_don)' },
      { name: 'id_danh_muc', label: 'ID Danh mục', keyboardType: 'numeric' },
      { name: 'id_nha_cung_cap', label: 'ID Nhà cung cấp', keyboardType: 'numeric' },
      { name: 'so_dang_ky', label: 'Số đăng ký' },
      { name: 'han_su_dung', label: 'Hạn sử dụng (YYYY-MM-DD)' },
      { name: 'trang_thai', label: 'Trạng thái (1: Hoạt động, 0: Tạm ngưng)', keyboardType: 'numeric' },
    ],
    columns: ['ten_thuoc', 'gia_ban', 'so_luong_ton', 'loai_ke_don'],
  },
  mo_ta_thuoc: {
    title: 'Mô tả chi tiết thuốc',
    resource: 'mo_ta_thuoc',
    label: 'mô tả thuốc',
    group: 'Dược phẩm & Kho',
    searchKeys: ['id_thuoc', 'thuong_hieu', 'thanh_phan', 'cong_dung'],
    fields: [
      { name: 'id_thuoc', label: 'ID Thuốc', keyboardType: 'numeric', required: true },
      { name: 'thuong_hieu', label: 'Thương hiệu / Hãng SX' },
      { name: 'dang_bao_che', label: 'Dạng bào chế (Viên nén/nang/sủi...)' },
      { name: 'quy_cach_dong_goi', label: 'Quy cách đóng gói' },
      { name: 'ham_luong', label: 'Hàm lượng hoạt chất' },
      { name: 'thanh_phan', label: 'Thành phần', multiline: true },
      { name: 'cong_dung', label: 'Công dụng chỉ định', multiline: true },
      { name: 'doi_tuong_su_dung', label: 'Đối tượng sử dụng' },
      { name: 'huong_dan_su_dung', label: 'Hướng dẫn sử dụng', multiline: true },
      { name: 'lieu_dung_khuyen_cao', label: 'Liều dùng khuyến cáo' },
      { name: 'bao_quan', label: 'Bảo quản' },
      { name: 'canh_bao', label: 'Cảnh báo & Chống chỉ định', multiline: true },
    ],
    columns: ['id_thuoc', 'thuong_hieu', 'dang_bao_che', 'cong_dung'],
  },
  danh_muc_thuoc: {
    title: 'Danh mục thuốc',
    resource: 'danh_muc_thuoc',
    label: 'danh mục',
    group: 'Dược phẩm & Kho',
    searchKeys: ['ten_danh_muc', 'mo_ta'],
    fields: [
      { name: 'ten_danh_muc', label: 'Tên danh mục', required: true },
      { name: 'mo_ta', label: 'Mô tả danh mục', multiline: true },
    ],
    columns: ['ten_danh_muc', 'mo_ta'],
  },
  anh_thuoc: {
    title: 'Hình ảnh thuốc',
    resource: 'anh_thuoc',
    label: 'ảnh thuốc',
    group: 'Dược phẩm & Kho',
    searchKeys: ['id_thuoc', 'duong_dan_anh'],
    fields: [
      { name: 'id_thuoc', label: 'ID Thuốc', keyboardType: 'numeric', required: true },
      { name: 'duong_dan_anh', label: 'Đường dẫn ảnh (URL)', required: true },
      { name: 'la_anh_chinh', label: 'Ảnh chính (1: Có, 0: Không)', keyboardType: 'numeric' },
      { name: 'thu_tu', label: 'Thứ tự hiển thị', keyboardType: 'numeric' },
    ],
    columns: ['id_thuoc', 'duong_dan_anh', 'la_anh_chinh'],
  },
  phieu_nhap_thuoc: {
    title: 'Phiếu nhập thuốc',
    resource: 'phieu_nhap_thuoc',
    label: 'phiếu nhập thuốc',
    group: 'Dược phẩm & Kho',
    searchKeys: ['id', 'id_nha_cung_cap', 'id_nhan_vien', 'ghi_chu'],
    fields: [
      { name: 'id_nha_cung_cap', label: 'ID Nhà cung cấp', keyboardType: 'numeric', required: true },
      { name: 'id_nhan_vien', label: 'ID Nhân viên nhập', keyboardType: 'numeric', required: true },
      { name: 'tong_tien', label: 'Tổng tiền nhập', keyboardType: 'numeric', required: true },
      { name: 'ngay_nhap', label: 'Ngày nhập' },
      { name: 'ghi_chu', label: 'Ghi chú', multiline: true },
    ],
    columns: ['id', 'id_nha_cung_cap', 'tong_tien', 'ngay_nhap'],
  },
  chi_tiet_phieu_nhap: {
    title: 'Chi tiết phiếu nhập',
    resource: 'chi_tiet_phieu_nhap',
    label: 'chi tiết phiếu nhập',
    group: 'Dược phẩm & Kho',
    searchKeys: ['id_phieu_nhap', 'id_thuoc', 'so_lo'],
    fields: [
      { name: 'id_phieu_nhap', label: 'ID Phiếu nhập', keyboardType: 'numeric', required: true },
      { name: 'id_thuoc', label: 'ID Thuốc', keyboardType: 'numeric', required: true },
      { name: 'so_luong', label: 'Số lượng nhập', keyboardType: 'numeric', required: true },
      { name: 'gia_nhap', label: 'Giá nhập', keyboardType: 'numeric', required: true },
      { name: 'so_lo', label: 'Số lô sản xuất' },
      { name: 'han_su_dung', label: 'Hạn sử dụng (YYYY-MM-DD)' },
    ],
    columns: ['id_phieu_nhap', 'id_thuoc', 'so_luong', 'gia_nhap', 'so_lo'],
  },
  lich_su_trang_thai_nhap: {
    title: 'Lịch sử nhập kho',
    resource: 'lich_su_trang_thai_nhap',
    label: 'lịch sử nhập',
    group: 'Dược phẩm & Kho',
    searchKeys: ['id_phieu_nhap', 'trang_thai', 'ghi_chu'],
    fields: [
      { name: 'id_phieu_nhap', label: 'ID Phiếu nhập', keyboardType: 'numeric', required: true },
      { name: 'trang_thai', label: 'Trạng thái (tao_moi / da_nhap_kho / da_huy)', required: true },
      { name: 'nguoi_cap_nhat', label: 'ID Người cập nhật', keyboardType: 'numeric' },
      { name: 'ghi_chu', label: 'Ghi chú', multiline: true },
      { name: 'thoi_gian_cap_nhat', label: 'Thời gian' },
    ],
    columns: ['id_phieu_nhap', 'trang_thai', 'thoi_gian_cap_nhat'],
  },

  // 2. Bán hàng & Đơn thuốc
  don_dat_thuoc: {
    title: 'Đơn đặt thuốc',
    resource: 'don_dat_thuoc',
    label: 'đơn đặt thuốc',
    group: 'Bán hàng & Đơn thuốc',
    searchKeys: ['id', 'id_khach_hang', 'dia_chi_giao_hang', 'so_dien_thoai_nhan', 'trang_thai'],
    fields: [
      { name: 'id_khach_hang', label: 'ID Khách hàng', keyboardType: 'numeric', required: true },
      { name: 'id_don_thuoc', label: 'ID Đơn thuốc kèm theo (nếu có)', keyboardType: 'numeric' },
      { name: 'id_khuyen_mai', label: 'ID Khuyến mãi', keyboardType: 'numeric' },
      { name: 'tong_tien', label: 'Tổng tiền', keyboardType: 'numeric', required: true },
      { name: 'giam_gia', label: 'Giảm giá', keyboardType: 'numeric' },
      { name: 'thanh_tien', label: 'Thành tiền', keyboardType: 'numeric', required: true },
      { name: 'dia_chi_giao_hang', label: 'Địa chỉ giao hàng', multiline: true, required: true },
      { name: 'so_dien_thoai_nhan', label: 'Số điện thoại nhận', required: true },
      { name: 'trang_thai', label: 'Trạng thái (cho_xac_nhan/dang_giao/hoan_thanh/da_huy)' },
      { name: 'ngay_dat', label: 'Ngày đặt' },
    ],
    columns: ['id', 'dia_chi_giao_hang', 'thanh_tien', 'trang_thai'],
  },
  chi_tiet_don_dat: {
    title: 'Chi tiết đơn đặt',
    resource: 'chi_tiet_don_dat',
    label: 'chi tiết đơn đặt',
    group: 'Bán hàng & Đơn thuốc',
    searchKeys: ['id_don_dat', 'id_thuoc'],
    fields: [
      { name: 'id_don_dat', label: 'ID Đơn đặt', keyboardType: 'numeric', required: true },
      { name: 'id_thuoc', label: 'ID Thuốc', keyboardType: 'numeric', required: true },
      { name: 'so_luong', label: 'Số lượng', keyboardType: 'numeric', required: true },
      { name: 'don_gia', label: 'Đơn giá', keyboardType: 'numeric', required: true },
    ],
    columns: ['id_don_dat', 'id_thuoc', 'so_luong', 'don_gia'],
  },
  don_thuoc: {
    title: 'Đơn thuốc (Toa bác sĩ)',
    resource: 'don_thuoc',
    label: 'đơn thuốc',
    group: 'Bán hàng & Đơn thuốc',
    searchKeys: ['id', 'id_khach_hang', 'id_bac_si', 'trang_thai'],
    fields: [
      { name: 'id_khach_hang', label: 'ID Khách hàng', keyboardType: 'numeric', required: true },
      { name: 'id_bac_si', label: 'ID Bác sĩ kê đơn', keyboardType: 'numeric', required: true },
      { name: 'ngay_ke_don', label: 'Ngày kê đơn (YYYY-MM-DD)' },
      { name: 'trang_thai', label: 'Trạng thái (cho_duyet / da_duyet / tu_choi)' },
      { name: 'id_nhan_vien_duyet', label: 'ID Dược sĩ duyệt', keyboardType: 'numeric' },
      { name: 'ngay_duyet', label: 'Ngày duyệt' },
      { name: 'ghi_chu_duyet', label: 'Ghi chú duyệt', multiline: true },
    ],
    columns: ['id', 'id_khach_hang', 'id_bac_si', 'trang_thai', 'ngay_ke_don'],
  },
  chi_tiet_don_thuoc: {
    title: 'Chi tiết toa thuốc',
    resource: 'chi_tiet_don_thuoc',
    label: 'chi tiết toa',
    group: 'Bán hàng & Đơn thuốc',
    searchKeys: ['id_don_thuoc', 'id_thuoc', 'lieu_dung'],
    fields: [
      { name: 'id_don_thuoc', label: 'ID Đơn thuốc', keyboardType: 'numeric', required: true },
      { name: 'id_thuoc', label: 'ID Thuốc', keyboardType: 'numeric', required: true },
      { name: 'so_luong_ke', label: 'Số lượng kê', keyboardType: 'numeric', required: true },
      { name: 'lieu_dung', label: 'Liều dùng & chỉ định', multiline: true, required: true },
      { name: 'so_ngay_dung', label: 'Số ngày dùng', keyboardType: 'numeric' },
    ],
    columns: ['id_don_thuoc', 'id_thuoc', 'so_luong_ke', 'lieu_dung'],
  },
  lich_su_theo_doi_don: {
    title: 'Lịch sử giao hàng',
    resource: 'lich_su_theo_doi_don',
    label: 'lịch sử đơn',
    group: 'Bán hàng & Đơn thuốc',
    searchKeys: ['id_don_dat', 'trang_thai_cap_nhat', 'ghi_chu'],
    fields: [
      { name: 'id_don_dat', label: 'ID Đơn đặt', keyboardType: 'numeric', required: true },
      { name: 'trang_thai_cap_nhat', label: 'Trạng thái (cho_xac_nhan/dang_giao/hoan_thanh/da_huy)', required: true },
      { name: 'ghi_chu', label: 'Ghi chú cập nhật', multiline: true },
      { name: 'thoi_gian_cap_nhat', label: 'Thời gian cập nhật' },
    ],
    columns: ['id_don_dat', 'trang_thai_cap_nhat', 'thoi_gian_cap_nhat'],
  },
  gio_hang: {
    title: 'Giỏ hàng người dùng',
    resource: 'gio_hang',
    label: 'giỏ hàng',
    group: 'Bán hàng & Đơn thuốc',
    searchKeys: ['id_khach_hang', 'id_thuoc'],
    fields: [
      { name: 'id_khach_hang', label: 'ID Khách hàng', keyboardType: 'numeric', required: true },
      { name: 'id_thuoc', label: 'ID Thuốc', keyboardType: 'numeric', required: true },
      { name: 'so_luong', label: 'Số lượng', keyboardType: 'numeric', required: true },
    ],
    columns: ['id', 'id_khach_hang', 'id_thuoc', 'so_luong'],
  },

  // 3. Tài chính & Khuyến mãi
  hoa_don: {
    title: 'Hóa đơn bán hàng',
    resource: 'hoa_don',
    label: 'hóa đơn',
    group: 'Tài chính & Khuyến mãi',
    searchKeys: ['id', 'so_hoa_don', 'id_don_dat'],
    fields: [
      { name: 'id_don_dat', label: 'ID Đơn đặt thuốc', keyboardType: 'numeric', required: true },
      { name: 'so_hoa_don', label: 'Số hóa đơn (e.g. HD2026000001)', required: true },
      { name: 'tong_tien_truoc_thue', label: 'Tổng tiền trước thuế', keyboardType: 'numeric' },
      { name: 'thue_vat', label: 'Thuế VAT', keyboardType: 'numeric' },
      { name: 'tong_tien_sau_thue', label: 'Tổng tiền sau thuế', keyboardType: 'numeric', required: true },
      { name: 'ngay_lap', label: 'Ngày lập hóa đơn' },
    ],
    columns: ['so_hoa_don', 'id_don_dat', 'tong_tien_sau_thue', 'ngay_lap'],
  },
  thanh_toan: {
    title: 'Giao dịch thanh toán',
    resource: 'thanh_toan',
    label: 'giao dịch thanh toán',
    group: 'Tài chính & Khuyến mãi',
    searchKeys: ['id_don_dat', 'phuong_thuc', 'ma_giao_dich', 'trang_thai'],
    fields: [
      { name: 'id_don_dat', label: 'ID Đơn đặt thuốc', keyboardType: 'numeric', required: true },
      { name: 'phuong_thuc', label: 'Phương thức (tien_mat / vi_dien_tu / chuyen_khoan)', required: true },
      { name: 'ma_giao_dich', label: 'Mã giao dịch' },
      { name: 'so_tien', label: 'Số tiền thanh toán', keyboardType: 'numeric', required: true },
      { name: 'trang_thai', label: 'Trạng thái (da_thanh_toan / cho_thanh_toan / that_bai)' },
      { name: 'thoi_gian_thanh_toan', label: 'Thời gian thanh toán' },
    ],
    columns: ['id_don_dat', 'phuong_thuc', 'so_tien', 'trang_thai'],
  },
  khuyen_mai: {
    title: 'Khuyến mãi & Voucher',
    resource: 'khuyen_mai',
    label: 'mã khuyến mãi',
    group: 'Tài chính & Khuyến mãi',
    searchKeys: ['ma_code', 'mo_ta', 'loai_giam'],
    fields: [
      { name: 'ma_code', label: 'Mã voucher (e.g. CHAOMUNG10)', required: true },
      { name: 'mo_ta', label: 'Mô tả điều kiện', multiline: true },
      { name: 'loai_giam', label: 'Loại giảm (phan_tram / so_tien)', required: true },
      { name: 'gia_tri_giam', label: 'Giá trị giảm (% hoặc VNĐ)', keyboardType: 'numeric', required: true },
      { name: 'don_toi_thieu', label: 'Đơn hàng tối thiểu (VNĐ)', keyboardType: 'numeric' },
      { name: 'ngay_bat_dau', label: 'Ngày bắt đầu (YYYY-MM-DD)' },
      { name: 'ngay_ket_thuc', label: 'Ngày kết thúc (YYYY-MM-DD)' },
      { name: 'so_luong_toi_da', label: 'Số lượng tối đa', keyboardType: 'numeric' },
    ],
    columns: ['ma_code', 'loai_giam', 'gia_tri_giam', 'don_toi_thieu'],
  },

  // 4. Đối tác & Hệ thống
  nha_cung_cap: {
    title: 'Nhà cung cấp',
    resource: 'nha_cung_cap',
    label: 'nhà cung cấp',
    group: 'Đối tác & Hệ thống',
    searchKeys: ['ten_nha_cung_cap', 'so_dien_thoai', 'email', 'nguoi_lien_he'],
    fields: [
      { name: 'ten_nha_cung_cap', label: 'Tên nhà cung cấp', required: true },
      { name: 'ma_so_thue', label: 'Mã số thuế' },
      { name: 'so_dien_thoai', label: 'Số điện thoại' },
      { name: 'email', label: 'Email' },
      { name: 'dia_chi', label: 'Địa chỉ', multiline: true },
      { name: 'nguoi_lien_he', label: 'Người liên hệ' },
      { name: 'trang_thai', label: 'Trạng thái (1: Hợp tác, 0: Tạm ngưng)', keyboardType: 'numeric' },
    ],
    columns: ['ten_nha_cung_cap', 'so_dien_thoai', 'nguoi_lien_he'],
  },
  bac_si: {
    title: 'Bác sĩ',
    resource: 'bac_si',
    label: 'bác sĩ',
    group: 'Đối tác & Hệ thống',
    searchKeys: ['ho_ten', 'chuyen_khoa', 'so_dien_thoai', 'so_chung_chi_hanh_nghe'],
    fields: [
      { name: 'ho_ten', label: 'Họ tên bác sĩ', required: true },
      { name: 'chuyen_khoa', label: 'Chuyên khoa' },
      { name: 'so_dien_thoai', label: 'Số điện thoại' },
      { name: 'so_chung_chi_hanh_nghe', label: 'Số CCHN', required: true },
      { name: 'id_tai_khoan', label: 'ID Tài khoản liên kết', keyboardType: 'numeric' },
    ],
    columns: ['ho_ten', 'chuyen_khoa', 'so_dien_thoai', 'so_chung_chi_hanh_nghe'],
  },
  khach_hang: {
    title: 'Khách hàng',
    resource: 'khach_hang',
    label: 'khách hàng',
    group: 'Đối tác & Hệ thống',
    searchKeys: ['ho_ten', 'so_dien_thoai', 'email', 'dia_chi'],
    fields: [
      { name: 'ho_ten', label: 'Họ và tên', required: true },
      { name: 'so_dien_thoai', label: 'Số điện thoại' },
      { name: 'email', label: 'Email' },
      { name: 'dia_chi', label: 'Địa chỉ nhận hàng', multiline: true },
      { name: 'ngay_sinh', label: 'Ngày sinh (YYYY-MM-DD)' },
      { name: 'id_tai_khoan', label: 'ID Tài khoản', keyboardType: 'numeric' },
    ],
    columns: ['ho_ten', 'so_dien_thoai', 'email'],
  },
  nhan_vien: {
    title: 'Nhân viên & Dược sĩ',
    resource: 'nhan_vien',
    label: 'nhân viên',
    group: 'Đối tác & Hệ thống',
    searchKeys: ['ho_ten', 'so_dien_thoai', 'email'],
    fields: [
      { name: 'ho_ten', label: 'Họ và tên', required: true },
      { name: 'so_dien_thoai', label: 'Số điện thoại' },
      { name: 'email', label: 'Email' },
      { name: 'id_tai_khoan', label: 'ID Tài khoản', keyboardType: 'numeric' },
    ],
    columns: ['ho_ten', 'so_dien_thoai', 'email'],
  },
  tai_khoan: {
    title: 'Tài khoản đăng nhập',
    resource: 'tai_khoan',
    label: 'tài khoản',
    group: 'Đối tác & Hệ thống',
    searchKeys: ['ten_dang_nhap', 'id_vai_tro'],
    fields: [
      { name: 'ten_dang_nhap', label: 'Tên đăng nhập', required: true },
      { name: 'mat_khau', label: 'Mật khẩu', required: true },
      { name: 'id_vai_tro', label: 'ID Vai trò (1: Khách, 2: Bác sĩ, 3: QL, 4: Dược sĩ, 5: Admin)', keyboardType: 'numeric', required: true },
      { name: 'trang_thai', label: 'Trạng thái (1: Hoạt động, 0: Khóa)', keyboardType: 'numeric' },
      { name: 'ngay_tao', label: 'Ngày tạo' },
    ],
    columns: ['ten_dang_nhap', 'id_vai_tro', 'trang_thai'],
  },
  vai_tro: {
    title: 'Vai trò & Phân quyền',
    resource: 'vai_tro',
    label: 'vai trò',
    group: 'Đối tác & Hệ thống',
    searchKeys: ['ten_vai_tro'],
    fields: [
      { name: 'ten_vai_tro', label: 'Tên vai trò', required: true },
    ],
    columns: ['id', 'ten_vai_tro'],
  },
  danh_gia: {
    title: 'Đánh giá & Nhận xét',
    resource: 'danh_gia',
    label: 'đánh giá',
    group: 'Đối tác & Hệ thống',
    searchKeys: ['id_thuoc', 'noi_dung'],
    fields: [
      { name: 'id_thuoc', label: 'ID Thuốc', keyboardType: 'numeric', required: true },
      { name: 'id_khach_hang', label: 'ID Khách hàng', keyboardType: 'numeric', required: true },
      { name: 'so_sao', label: 'Số sao đánh giá (1-5)', keyboardType: 'numeric', required: true },
      { name: 'noi_dung', label: 'Nội dung nhận xét', multiline: true, required: true },
      { name: 'ngay_danh_gia', label: 'Ngày đánh giá' },
    ],
    columns: ['id_thuoc', 'so_sao', 'noi_dung', 'ngay_danh_gia'],
  },
  v_thuoc_ke_don: {
    title: 'View: Thuốc kê đơn (ETC)',
    resource: 'v_thuoc_ke_don',
    label: 'thuốc kê đơn',
    group: 'Dược phẩm & Kho',
    searchKeys: ['ten_thuoc', 'so_dang_ky'],
    fields: [
      { name: 'ten_thuoc', label: 'Tên thuốc', required: true },
      { name: 'so_dang_ky', label: 'Số đăng ký' },
    ],
    columns: ['id', 'ten_thuoc', 'so_dang_ky'],
  },
  v_thuoc_sap_het_han: {
    title: 'View: Thuốc sắp hết hạn',
    resource: 'v_thuoc_sap_het_han',
    label: 'thuốc sắp hết hạn',
    group: 'Dược phẩm & Kho',
    searchKeys: ['ten_thuoc', 'han_su_dung'],
    fields: [
      { name: 'ten_thuoc', label: 'Tên thuốc', required: true },
      { name: 'han_su_dung', label: 'Hạn sử dụng' },
      { name: 'so_luong_ton', label: 'Số lượng tồn', keyboardType: 'numeric' },
    ],
    columns: ['id', 'ten_thuoc', 'han_su_dung', 'so_luong_ton'],
  },
};
